plugins {
    id 'java'
    id 'application'
}

group = 'com.mk.ukim.finki'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.clickhouse:clickhouse-jdbc:0.10.0:all'
    implementation 'org.postgresql:postgresql:42.7.13'
}

application {
    mainClass = 'com.mk.ukim.finki.BenchmarkRunner'
}